name: Build
on:
  push:
jobs:
  build-project-ubuntu:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.6

      - name: Configure and Build Project
        uses: threeal/cmake-action@main

      - name: Save build folder as artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_folder
          path: build/

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/AutoIP