name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  
jobs:
  msvc2019:
    runs-on: windows-2019
    strategy:
      matrix:
        build_type: [Debug, Release]
        architecture: [x64]

    steps:
    - uses: actions/checkout@v3
    - name: Run CMake
      run: cmake -S . -B build -G "Visual Studio 17 2022" -DCMAKE_CXX_FLAGS="/std:c++latest"
    - name: Build
      run: cmake --build build --config Release --parallel 10
